apiVersion: v1
kind: ConfigMap
metadata:
  name: tickets-api-config
  namespace: tickets-system
data:
  NODE_ENV: "production"
  API_PORT: "3010"
  # Configurações do PostgreSQL
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "tickets_db"
  POSTGRES_USER: "tickets"
  # Configurações do Redis
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379" 