apiVersion: v1
kind: Secret
metadata:
  name: tickets-api-secrets
  namespace: tickets-system
type: Opaque
data:
  # Base64 encoded values - ALTERE ESTES VALORES EM PRODUÇÃO!
  POSTGRES_PASSWORD: dGlja2V0c19zZWN1cmVfcGFzcw== # tickets_secure_pass
  REDIS_PASSWORD: cmVkaXNfc2VjdXJlX3Bhc3M= # redis_secure_pass
  JWT_SECRET: c3VwZXJfc2VjdXJlX2p3dF9zZWNyZXRfZm9yX3Byb2R1Y3Rpb24= # super_secure_jwt_secret_for_production
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: tickets-system
type: Opaque
data:
  POSTGRES_PASSWORD: dGlja2V0c19zZWN1cmVfcGFzcw== # tickets_secure_pass
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: tickets-system
type: Opaque
data:
  REDIS_PASSWORD: cmVkaXNfc2VjdXJlX3Bhc3M= # redis_secure_pass 